[platformio]
default_envs = esp32-c6

[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_upload.flash_size = 4MB

lib_deps =
    makuna/NeoPixelBus @ ^2.8.0
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -I include
    -D HYPERLED_SLAVE_VERSION=\"0.0.001\"

[env:esp32-c6]
board = esp32-c6-devkitc-1


